// <auto-generated />
namespace Mohawk.Jakab.Quizzard.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createdON : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createdON));
        
        string IMigrationMetadata.Id
        {
            get { return "201811290838480_createdON"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
